version: '3'
services:
  database:
    container_name: yii-basic-database
    image: "postgres" # use latest official postgres version
    volumes:
      - /var/lib/postgresql/data/ # persist data even if container shuts down
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: su
      POSTGRES_DB: basic_database
    ports:
      - '5431:5432'
  php:
    container_name: yii-basic-app
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'